name: Lint Python
on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  PythonLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check code lints with Black
        uses: jpetrucciani/black-check@master
