name: nf-core/tools API docs
on:
  push:
    branches: [master, dev]

jobs:
  api-docs:
    name: Build & push Sphinx API docs
    runs-on: ubuntu-18.04

    steps:
      - name: Check out source-code repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip Sphinx sphinxcontrib-napoleon
          pip install .

      - name: Build HTML docs
        run: make --directory ./docs/api html

      - name: Push docs to api-doc branch
        if: github.repository == 'nf-core/tools'
        run: |
          git checkout --orphan api-doc
          git rm -r --cache .
          git config user.email "core@nf-co.re"
          git config user.name "nf-core-bot"
          git add docs
          git commit --message "nf-core/tools docs build

          $GITHUB_REF - $GITHUB_SHA
          "
          git remote add nf-core https://github.com/nf-core/tools.git
          git push --force --set-upstream nf-core api-doc
